export const plans = [
  {
    name: "BÁSICO",
    description: "Presencia profesional.",
    items: [
      "Landing page profesional",
      "WhatsApp integrado",
      "Diseño responsive",
      "SEO básico",
      "Entrega en 7–10 días",
      "1 ronda de cambios",
      "Soporte básico (15 días)",
    ],
    price: "$4,990",
    currency: "MXN",
    note: "Pago único",
    cta: "COTIZAR",
    recommended: false,
    plus: false,
    whatsappMessage:
      "Hola, me interesa el plan Básico de OCTO por $4,990 MXN. Me gustaría recibir información y cotización.",
  },
  {
    name: "CRECIMIENTO",
    description: "Captación de clientes.",
    items: [
      "Sitio web completo (hasta 5 páginas)",
      "WhatsApp integrado",
      "SEO inicial (On-page)",
      "Formulario de contacto",
      "Integración con Google Maps",
      "Entrega en 10–14 días",
      "2 rondas de cambios",
      "Soporte y mantenimiento (60 días)",
    ],
    price: "$8,490",
    currency: "MXN",
    note: "Pago único",
    cta: "COTIZAR",
    recommended: false,
    plus: false,
    whatsappMessage:
      "Hola, me interesa el plan Crecimiento de OCTO por $8,490 MXN. Quiero conocer qué incluye y cómo podemos empezar.",
  },
  {
    name: "OCTO",
    description: "Relación continua.",
    items: [
      "Sitio web completo",
      "WhatsApp + automatizaciones",
      "SEO avanzado",
      "Integración con Google Maps",
      "Cambios y actualizaciones continuas",
      "Soporte continuo",
      "Optimización y mejoras mensuales",
      "Reportes de rendimiento",
      "Integraciones avanzadas",
      "Entrega en 7–10 días",
    ],
    price: "$2,990",
    currency: "MXN",
    note: "Configuración inicial",
    monthlyPrice: "$1,490",
    monthlyNote: "MXN / mes",
    cta: "COTIZAR",
    recommended: true,
    plus: true,
    whatsappMessage:
      "Hola, me interesa OCTO+. Vi que la configuración inicial es de $2,990 MXN y la mensualidad de $1,490 MXN. Quiero conocer qué incluye y cómo podemos empezar.",
  },
] as const;
